### ISSUE TITLE
Caching Definition and Implementation

### ISSUE THREAD

**Issue by derrysmith** [derrysmith/dscorlib#9]
> As a developer, I would like to code against an interface that provides __caching__ functionality, so that I can increase the performance in my applications but storing/retrieving objects from a cache.

## Tasks
- [ ] Create ICachingProvider interface
- [ ] Implement ICachingProvider using an InMemory implementation
- [ ] Implement ICachingProvider using a Couchbase implementation
